version: "3.7"
services:
  app:
    image: node:alpine
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
    working_dir: /app
    command: sh -c 'yarn && node_modules/.bin/nodemon src/server'
