version: "3.7"
services:
  redis:
    image: redis:alpine
    expose:
      - 6379
  app:
    depends_on:
      - redis
    image: node:alpine
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://redis
    working_dir: /app
    command: sh -c 'yarn && node_modules/.bin/nodemon src/server'
