version: "3.7"
services:
  app:
    build: ./
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: sh -c 'yarn && node_modules/.bin/nodemon src/server'
